### ISSUE TITLE
No Yolo inference with default code.]

### ISSUE THREAD

**Issue by BerryTsai** [toolboc/IntelligentEdgeHOL#2]
Hi, I am Berry Tsai from Microsoft Taiwan. I tried your code with my Jetson Nano. It did download the youtube video & play. But the Yolo/darknet not works. I checked the code. Look like the "Inference" is "False". 
So i try add "INFERENCE=True" in deployment.json. It works now.

And the USB camera in Jetson Nano is "/dev/vidoe1".
edgeAgent and edgHub have 1.0.8 release version for ARM64V8.
"mcr.microsoft.com/azureiotedge-agent:1.0.8-linux-arm64v8"
"mcr.microsoft.com/azureiotedge-hub:1.0.8-linux-arm64v8"

![yolo](https://user-images.githubusercontent.com/34261469/62699927-2df9c780-ba13-11e9-9571-26e7e1f52b4d.jpg)

**Comment by toolboc** [comment]
@BerryTsai ,

My apoologies for any issues encountered, we do specify in the instructions that the module twin requires an update of the `Inference` property in order to enable the object detection but I agree that this step may be unnecessary and confusing as-is.

Inference should be enabled by default now with this changeset https://github.com/toolboc/IntelligentEdgeHOL/commit/b5e1ba2d9defaffe5018b8568303cc00779f5153

Regarding the USB Camera, the enumerated value `/dev/video0` could vary with different hardware configurations.  Perhaps we can add a note in the README to enumerate available video devices using ``` ls -ltrh /dev/video* ```

**Comment by BerryTsai** [comment]
The USB camera. I think i have mount MIPI and USB camera both. So my USB show video1
