### ISSUE TITLE
Socketio errors

### ISSUE THREAD

**Issue by micuentadecasa** [toolboc/IntelligentEdgeHOL#6]
Hi, after installing, everything seems ok, but after printing the VideoCapture message, it gives multiple errors like these:

Error: Time:Mon Jun 22 13:40:00 2020 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:380 Failure: connect failure 111.
Error: Time:Mon Jun 22 13:40:15 2020 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Jun 22 13:40:15 2020 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Mon Jun 22 13:40:15 2020 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Mon Jun 22 13:40:15 2020 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2151 failure connecting to address xxxx.

I've tried to modify the tiwin module to do inference, but it doesn't works, it doesn't download the twin, maybe for this connection errors..., but my jetson doesn't give errors when downloading the modules, or downloading the video, etc...

Regards.

**Comment by jimbobbennett** [comment]
Hey @micuentadecasa,

This is caused by the manifest using an older version of the edge agent and hub. The manifest uses 1.0.8 but the latest version is 1.0.9.

I've raised #8 with a more specific description of the error.

You can fix this in one of two ways:
* Update the version in the deployment template to 1.0 - this is a 'rolling version' and will use the latest 1.0, whatever that is at the time
* Downgrade your iotedge to 1.0.8

You can read about these versions in the [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge](https://docs.microsoft.com/azure/iot-edge/how-to-update-iot-edge?WT.mc_id=iotedge-github-jabenn) docs.

**Comment by micuentadecasa** [comment]
thanks @jimbobbennett .
